<a href="https://colab.research.google.com/github/VishalC02/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy**

In [6]:
import numpy as np

In [8]:
arr1=np.array([1,2,3,4,5])
arr1


array([1, 2, 3, 4, 5])

In [9]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3=np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

In [16]:
arr7=np.linspace(1,10,5)
arr7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr8=arr7.copy()
arr8

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
arr2.shape

(2, 3)

In [20]:
arr7.astype('int')

array([ 1,  3,  5,  7, 10])

In [21]:
lista=range(100)
arr9=np.arange(100)

In [22]:
import sys

In [24]:
print(sys.getsizeof(1)*len(lista))
print(arr9.size*arr9.itemsize)


2800
800


In [25]:
import time

In [26]:
x=range(1000)
y=range(1000,2000)
start_time=time.time()
z=[x+y for x,y in zip(x,y)]
print(time.time()-start_time)

0.00037169456481933594


In [27]:
y=np.arange(1000)
start_time=time.time()
z=x+y
print(time.time()-start_time)

0.0005249977111816406


In [30]:
arr10=np.arange(24).reshape(6,4)
arr10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
arr10[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [38]:
arr10[4:,2:]

array([[18, 19],
       [22, 23]])

In [39]:
for i in arr10:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [40]:
for i in np.nditer(arr10):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [41]:
import numpy as np

In [42]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [43]:
arr1>arr2

array([False, False, False, False, False])