<a href="https://colab.research.google.com/github/VishalC02/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Numpy
import numpy as np
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

type(arr)

print(arr)

arr.shape

[1 2 3 4 5]


(5,)

In [16]:
#Multinested array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

arr=np.array([my_list1,my_list2,my_list3])

arr
#Check the shape of array
arr.shape

#Reshape the array
arr.reshape(5,3)



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [24]:
#iIndexing
arr

arr[1:,3:]








IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [32]:

#Arange function
arr=np.arange(0,10,step=2)
arr

#Copy function

arr[3:]=100
arr
arr1=arr
print(arr1)
arr1=arr.copy()

arr[3:]=1000
arr





[  0   2   4 100 100]


array([   0,    2,    4, 1000, 1000])